name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      ETH_RPC_URL_MAINNET: ${{ secrets.ETH_RPC_URL_MAINNET }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge Minter tests
        run: |
          forge test test/HypMinter.t.sol
        id: test

      - name: Run Forge Minter simulation pipeline
        run: |
          ./script/pipeline.sh
        id: pipeline

      - name: Upload gnosis safe calldata
        uses: actions/upload-artifact@v4
        with:
          name: gnosis-transactions
          path: |
            schedule_transactions.json
            execute_network_transactions.json
            execute_minter_transactions.json
            execute_foundation_transactions.json

      - name: Run Forge Ownership Transfer simulation pipeline
        run: |
          ./script/pipeline2.sh
        id: pipeline2

      - name: Upload gnosis safe calldata
        uses: actions/upload-artifact@v4
        with:
          name: gnosis-transactions
          path: |
            script/calldata/schedule_transactions_timelock.json
